### ISSUE TITLE
Error using the harmony to tiff

### ISSUE THREAD

**Issue by CameliaMocanu** [TheJacksonLaboratory/phenix-service#2]
Hello,

I have exported the Index.xml file from Harmony and from my understanding this script should export the images in readable tiffs.

I tried running the script in python and got this error:

%tb
Traceback (most recent call last):

  File "C:\Users\3i\anaconda3\envs\perkin elmer\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "v:\harmony\referenced images\__2022-10-25t16_45_40-measurement 8b\images\pe2tif.py", line 162, in <module>
    main()

  File "v:\harmony\referenced images\__2022-10-25t16_45_40-measurement 8b\images\pe2tif.py", line 153, in main
    args = argparser.parse_args()

  File "C:\Users\3i\anaconda3\envs\perkin elmer\lib\argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)

  File "C:\Users\3i\anaconda3\envs\perkin elmer\lib\argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)

  File "C:\Users\3i\anaconda3\envs\perkin elmer\lib\argparse.py", line 2034, in _parse_known_args
    self.error(_('the following arguments are required: %s') %

  File "C:\Users\3i\anaconda3\envs\perkin elmer\lib\argparse.py", line 2521, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)

  File "C:\Users\3i\anaconda3\envs\perkin elmer\lib\argparse.py", line 2508, in exit
    _sys.exit(status)

SystemExit: 2

Apologies as I am a beginner in python, but can you please provide some guidance?

Many thanks!

**Comment by wflynny** [comment]
Hi @CameliaMocanu,

Are you by chance running the `harmony_to_tiff.py` script in a Jupyter Notebook?  If so, I'd refer to #1, where there's some advice on how to fix this issue, specifically:
https://github.com/TheJacksonLaboratory/phenix-service/issues/1#issuecomment-1200603136

> `harmony_to_tiff.py` is intended to be a commandline tool. You can either use IPython/Jupyter magic to do something like:

```
In [1]: import sys

In [2]: {sys.executable} /path/to/harmony_to_tiff.py convert ...
```
or you can import the relevant class from the file:
```
import sys
from pathlib import Path

sys.path.append("/path/to/utils/")
from harmony_to_tiff import HarmonyArchive

archive_location = Path("/where/your/files/are")
output_location = Path("/where/you/want/your/output")

archive = HarmonyArchive(archive_location)
archive.load_image_database()
archive.convert_to_human_readable(output_location)
```

**Comment by CameliaMocanu** [comment]
Hi @wflynny,

I was running it in Spyder actually. I have read in the thread you linked to, and I think I misunderstood what the purpose of the script is. I actually do not have harmony archives, but only the index.idx.xml files referencing the images. So when I tried to run the script there were many other errors. 

Sorry for the trouble!
